### ISSUE TITLE
Poor performance compared to welle-cli

### ISSUE THREAD

**Issue by andimik** [nRaecheR/dab_plus_streamer#3]
I have both tools on my Laptop: **welle-cli** and **dab_plus_streamer**.

Although **welle-cli** is working without any problems using the following command

```./welle-cli -c 6A -Dw 7979 -F rtl_tcp```

![Bildschirmfoto von 2022-03-14 20-14-44](https://user-images.githubusercontent.com/24510556/158245045-9c2bd0d1-2759-4ca9-8bce-a94f4fe025ce.png)

**dab_plus_streamer** is not working properly using the same connection and 

```./dab_plus_streamer -c 6A -Dw 7979 -F rtl_tcp```

![Bildschirmfoto von 2022-03-14 20-16-35](https://user-images.githubusercontent.com/24510556/158245347-05e3ffda-9d35-495a-b4a5-f1b659859a13.png)

Any chance to contribute to (well known) **welle-cli** instead of maintain a (nearly unknown) fork?

**Comment by nRaecheR** [comment]
The -D parameter and functionality will be removed completely because it makes no sense to decode all programs for a web streamer. The purpose of dab-plus-streamer is a different one compared to wello.io. I've forked it to modify it to be used as radio streaming server, not as diagnostic tool. Over the time there will be more changes that makes it incompatible on source level. I don't think it would make sense to merge it in the welle.io code base.
The conversion is far from finished, so you see a lot of bugs and rough edges, missing, removed or not working features.

**Comment by andimik** [comment]
Ok thank you for the answer. I just followed the help text.

```
Examples:

dab_plus_streamer -c 10B -p GRRIF -F rtl_tcp,localhost:1234
    Receive 'GRRIF' on channel '10B' using 'rtl_tcp' driver on localhost:1234.

dab_plus_streamer -c 10B -D 
    Dump FIC and all programmes of channel 10B to files.

dab_plus_streamer -c 10B -w 8000
    Enable web server on port 8000, decode programmes on channel 10B on demand
    (http://localhost:8000).

dab_plus_streamer -c 10B -Dw 8000
    Enable web server on port 8000, decode all programmes on channel 10B.
```

**Comment by nRaecheR** [comment]
Yes, you're right. The help text is mostly from welle.io and needs a rewrite. Thank you for the heads up.
